### ISSUE TITLE
Feature requests: Shortcuts for macOS

### ISSUE THREAD

**Issue by scheinercc** [ysard/cookie-quick-manager#11]
Heya,

The current shortcuts don't work on macOS. Ok, `Ctrl + F` does work. `Ctrl + left` and `Ctrl + right` is already used by the system to change between desktops, maybe it could be mapped to `Cmd + left/right`? There is no `super` key. Could this be mapped to the `delete` (equivalent of `backspace`) key?

Thanks

**Comment by ysard** [comment]
Hi this will be fixed in the next release (b127d48) with the availability of the meta key for MacOS systems :)
