### ISSUE TITLE
Add link to AMO to repo header

### ISSUE THREAD

**Issue by scheinercc** [ysard/cookie-quick-manager#13]
Heya,

 I saw that the README gets also used on AMO, so I'd suggest to add a link to the add-on page on AMO (https://addons.mozilla.org/firefox/addon/cookie-quick-manager/) to the repo header.
<img width="741" alt="image" src="https://user-images.githubusercontent.com/817856/39031790-a2aff2f2-44ad-11e8-9d21-374b196f41a0.png">

**Comment by ysard** [comment]
Hi ! First of all I would like to thank you for your suggestions!
I close the issue with a little delay; but I plan to resume development shortly :)
