### ISSUE TITLE
Feature requests: Select next item instead of previous

### ISSUE THREAD

**Issue by scheinercc** [ysard/cookie-quick-manager#15]
Heya,

When deleting one domain row which is not the first one, it would be great if the selection jumped to the next row not the previous. Lets say I keep cookies of domain 1 and 2, delete 3 and also want to delete 4 and 5, I would just have to select three and hit the bin three times.
Right now I either select them one by one (trying to be careful not to delete 2 - which happened to me a few times now already) or I select 5 and hit three times to the top.
This is for the both lists.

Thanks

**Comment by ysard** [comment]
Hi it should be ok now, i close the issue ;)
