### ISSUE TITLE
Better placement of bin icons

### ISSUE THREAD

**Issue by scheinercc** [ysard/cookie-quick-manager#17]
@ysard - the three different bins are a bit confusing, especially the middle one, maybe it is just me. When I select the domain of the left pane I expet the bin underneath to be the one to delete the selected item, same for the middle column. When one cookie is highlighted there, I also expect the bin underneath to be responsible for the one highlighted.

That's why I moved the bins one to the left and the icons related to all domains underneath a border (the UI is not prefect, just as an idea for discussion).

<img width="1367" alt="image" src="https://user-images.githubusercontent.com/817856/39397532-27674c42-4b44-11e8-8fa6-18da26139d33.png">

Alternatively I could imagine the "delete all cookies" and the "delete all from domain" to be disabled by default and have a tick box each which selects all related items and give a visual from what will happen if you click.

**Comment by practik** [comment]
I find these icons confusing too. Here is what I would intuitively expect from their current positions:

- left button: deletes all the cookies of the domain(s) selected in the Domains list
- middle button: deletes only the specific cookie(s) selected in the Cookies list
- right button: ??? I would not expect to see a delete button here at all

Either of @scheinercc's suggestions would be an improvement.

**Comment by ysard** [comment]
Hi, there will be a contextual menu on the list of the domains with this option (among others). So i removed the bin under the second column.
