### ISSUE TITLE
Differenciate icons with submenues

### ISSUE THREAD

**Issue by scheinercc** [ysard/cookie-quick-manager#18]
The two icons "protect all" and the folder icon are the only two icons with
a) no immediate action on click, due to the submenu
b) no explanation on hover.

This confused me a bit and I also wasn't sure if I want to click, as I didn't know what will happen. I added two semi-well placed "chevron-up" icons trying to indicate the menu.

I would suggest to add something like these icons, but also add a description for consistency - can be something simple and generic as "click for more options".

<img width="1367" alt="image" src="https://user-images.githubusercontent.com/817856/39397532-27674c42-4b44-11e8-8fa6-18da26139d33.png">

**Comment by practik** [comment]
Shouldn't the chevrons/arrows point **down**, though? (Example: the Watch button at the top of this Github page.)

**Comment by scheinercc** [comment]
Yeap, you are right. Might have been the submenues opened above the button for me, still should point down

**Comment by ysard** [comment]
Hi, a chevron was put on these 2 buttons ( e5eefa4 ). I close the issue, thank you ;)
