### ISSUE TITLE
Add locales

### ISSUE THREAD

**Issue by Machou** [ysard/cookie-quick-manager#2]
Hello

I want translate you're addon in french, can you add locales files please

**Comment by ysard** [comment]
Hello, thank you for your helpful proposal, I am working on the internationalization of the application soon, mais je suis français alors je vais m'occuper de la traduction française dans la foulée :D

**Comment by Machou** [comment]
Ah ok :P pas de soucis alors. :)

Pour te motiver, dès que t'as fait les locales, je te ferai un petit don en Bitcoin

**Comment by ysard** [comment]
Merci ! La traduction semble être terminée pour le moment : v0.1rc2 !

Je clos l'issue ;)
