### ISSUE TITLE
Tab key navigation skips Cookies list

### ISSUE THREAD

**Issue by practik** [ysard/cookie-quick-manager#20]
Steps to reproduce:

1. Open the cookie manager window. The Domains list has focus.
2. Press the Tab key.

Expected results: Focus should always move to the next area of the interface, which is the Cookies list.
Actual results: If the Cookies list for the currently selected domain is long enough to require a scrollbar, focus moves to the Cookies list as expected. But if there is no scrollbar (which is most of the time, for me), focus skips over the Cookies list and moves directly to the Domain field under Details.

Cookie Quick Manager 0.2rc3 on Firefox 60.0.1 on macOS

**Comment by ysard** [comment]
Hi, this will be fixed with #21, thank you :)
