### ISSUE TITLE
buttons not highlighted when focused

### ISSUE THREAD

**Issue by practik** [ysard/cookie-quick-manager#21]
Steps to reproduce:

1. Open the cookie manager window. The Domains list has focus.
2. Press the Tab key repeatedly, moving focus through the various areas of the interface, until the Sub-domains checkbox beside the Search box is highlighted.
3. Press the Tab key again.

Expected results: Some other part of the interface should be highlighted in some way to show the user where focus now is.
Actual results: For the next 10 presses of the Tab key, there is no visual indicator of focus anywhere in the window. Only on the 11th press does focus return to the Domains list.

By experimenting, I discovered that after the Sub-domains checkbox, focus moves through the 10 buttons at the bottom of the window. Three of those buttons delete cookies! A user could easily delete some or all of their cookies by accident as a result of this bug.

Cookie Quick Manager 0.2rc3 on Firefox 60.0.1 on macOS

**Comment by ysard** [comment]
Hi, i see what you mean; the choice of the css class "btn-dark" for the buttons makes invisible the display change of during focus change.

The default class is much more explicit about this; examples here:
https://getbootstrap.com/docs/3.3/css/#buttons
https://www.w3schools.com/bootstrap/bootstrap_buttons.asp

For now, I keep the current class but I will add a dark border in the focus.

PS: Feel free to reopen this issue if satisfying
