### ISSUE TITLE
up and down arrows only work in Domains list (possibly Mac-specific)

### ISSUE THREAD

**Issue by practik** [ysard/cookie-quick-manager#22]
Steps to reproduce:

1. Open the cookie manager window. The Domains list has focus.
2. Select a domain whose Cookies list is long enough to require a scrollbar (see #20).
3. Press the Tab key to move focus to the Cookies list. The first cookie in the list is selected.
4. Press the down arrow key.

Expected results: The next cookie in the Cookies list is selected.
Actual results: The next domain in the Domains list is selected.

As noted at #11, the `ctrl+right` shortcut doesn't work on macOS, so the Tab key is the only way to switch to the Cookies list on a Mac. So perhaps the up and down arrow keys work properly when using the official shortcut, but I can't test that.

Cookie Quick Manager 0.2rc3 on Firefox 60.0.1 on macOS

PS: This is an essential extension now that Mozilla has removed this functionality from Firefox itself – thank you for creating it!

**Comment by ysard** [comment]
Thank you for your report, the bug is not due to your system but more to a poor focus management :)
This will be fixed in the new version.
The tab key and the combination shift + tab will switch between the list of cookies and the list of domains.
Thank you for your encouragements :)
