### ISSUE TITLE
Doesn't seem to work at all

### ISSUE THREAD

**Issue by rmenessec** [ysard/cookie-quick-manager#23]
The manager window doesn't display any cookies. Searching doesn't appear to work. The "refresh" button doesn't populate a list of domains, or have any other obvious effect. In short, the addon doesn't seem to work.

Firefox Developer Edition 61.0b7 x64, Windows 10 x64.

**Comment by ysard** [comment]
Hi !
I just read your review of AMO, thanks for the bug report, the extension displays the cookies on Firefox public releases 56, 58 and 60 (the versions on which I do my tests (on Linux)).; BUT you are the second person to report this behavior :/

The search can not work if the list of domains on the left is empty.
The "refresh" button queries all cookies via the mozilla API, there is no other way to do it.

So, the first explanation is that there is no cookie on the browser, but that would probably be a little too easy.
When you go into browser preferences, select the Privacy & Security panel and go to the Cookies and Site Data section (http://support.mozilla.org/en-US/kb/cookies-information-websites -store-on-your-computer # w_cookie-settings);
there is a button: "manage the data"
Is there any cookie in the displayed list?

If yes, then there is indeed a problem with the addon and i will try a test on your specific version.
Maybe the API is different on it.
I'm going to look on my side.

**Comment by ysard** [comment]
Ok I found the explanation, you have the option FPI (First Party Isolation) enabled by default on your browser.

https://www.bleepingcomputer.com/news/software/another-tor-browser-feature-makes-it-into-firefox-first-party-isolation/
https://www.ghacks.net/2017/11/22/how-to-enable-first-party-isolation-in-firefox/

Currently the addon does not support it (the API only allows this since version 59).
I will work on it.
In the meantime, you can temporarily disable the option to enjoy the addon if you wish :)

**Comment by rmenessec** [comment]
Ah. I can see how that might be a problem. Thanks for looking into this. I've updated my review accordingly.

**Comment by ysard** [comment]
Thank you for the update of the review :)

Some news here: the development is facing what I think is a bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1465063

I'm waiting for news from the developers.

**Comment by ysard** [comment]
Hi, some news here, the bug should be fixed on Firefox 62 scheduled for September 2018.
Until that the activation of the FPI option will cause some bugs with my addon, but will be supported.

**Comment by rmenessec** [comment]
Thanks for the update! I'm using Developer Edition, so I guess I'll get a chance to try that out in the next week or so. 😊

**Comment by ysard** [comment]
Solved in Firefox62
