### ISSUE TITLE
cookie counter is not updated when cookies are deleted

### ISSUE THREAD

**Issue by practik** [ysard/cookie-quick-manager#24]
Steps to reproduce:

1. In the cookie manager window, choose a domain in the Domains list and note the number of cookies.
2. Delete one cookie from that domain, then look at its cookie counter again.

Expected results: The number on the counter should be one less than it was before.
Actual results: The number is the same as before. The only way to update it is to refresh the domain list.

Cookie Quick Manager 0.2rc3 on Firefox 60.0.1 on macOS

**Comment by ysard** [comment]
Hi, thank you for the report it was a necessary finishing :)
