### ISSUE TITLE
clarify shortcut key names

### ISSUE THREAD

**Issue by practik** [ysard/cookie-quick-manager#26]
@ysard, thank you for fixing these bugs so quickly!

I just took a quick look at the commit that fixed #20 and #21, and I have two more suggestions:

Instead of `maj+tab`, maybe `⇧+tab` would be better for users who don't speak French.

You might also want to change `suppr`– I noticed that @scheinercc was confused by this in #11 (he wrote: "There is no `super` key"). Unfortunately I don't know of any symbol for this one, but since the rest of the preferences are in English, you could change it to `delete` or just `del`.

**Comment by ysard** [comment]
Sorry I missed the problem with the delete key on MacOS, this should be solved with 87fb633.
