### ISSUE TITLE
Compatibility & Feature request

### ISSUE THREAD

**Issue by thomaszimm** [ysard/cookie-quick-manager#28]
Hi, first of all I would like to thank you very much for your hard work with developing this addon! It is extremely important, since it is one of only two addons that lets me export and import cookies without issues.
My organisation is using this addon hundreds of times a day and I even have python automations that rely on it So, thank you!

I noticed there was a new update issued a few days ago. Before I update to the latest version, I wanted to ask if it is 100% compatible with the previous one? So, if I export cookies with the updates addon, can I import them again with the previous addon, without issues?

Another idea to make it even more perfect: Could you create keyboard shortcuts for exporting and importing cookies? I saw some shortcuts are available already, so maybe it's not hard to do. If I export/import cookies manually, this would save a lot of time.

Thanks and keep up the good work! :)

**Comment by ysard** [comment]
Hi, thank you for your review it is good to see that people use this work :)

- About compatibility of the JSON file:
From old version -> new version:
Cookies without Contextual Identity will be imported into the default one, and cookies without First-Party Domain field, will be imported as normal cookies.
From new version -> old version:
First-Party Domain field will not be read

Moreover, I will look to introduce shortcuts like Ctrl+O/Ctrl+S to import/export cookies.
