### ISSUE TITLE
Multiple highlighting of cookies

### ISSUE THREAD

**Issue by nollinvoyd** [ysard/cookie-quick-manager#29]
It would be quite helpful to have the ability to highlight multiple cookies simultaneously when performing such actions as protect, etc.

thanks

**Comment by ysard** [comment]
Hi, your request seems to be the same as #9 , i will try work on it in the future but it's tricky for the moment :)

**Comment by ysard** [comment]
I'm closing the issue because the same enhancement is mentioned on #12 :)
