### ISSUE TITLE
Feature request: Open cookie manager in new tab

### ISSUE THREAD

**Issue by laniakea64** [ysard/cookie-quick-manager#4]
First off I want to say thank you @ysard for a very nice cookie manager! 😃 

Unfortunately, in Linux the cookie manager window is forced on top of the parent browser window.  You can't put the browser window in front of it.  I don't have a very big screen, so this makes it awkward to do anything in the browser while the cookie manager is open.  This includes accessing the options by clicking the wrench icon in the cookie manager.

Can you please provide the option to open the cookie manager in a new tab instead?

Thanks!

**Comment by ysard** [comment]
Hello, happy yo see that you are using the addon !

> Can you please provide the option to open the cookie manager in a new tab instead?

Ok i will work on this option :)

**Comment by Alhaitham** [comment]
In the meantime, you can open the cookie manager in a new tab by using this:

`moz-extension://5329b823-4569-4e85-a9b3-052f26baf772/cookies.html?parent_url=`

**Comment by laniakea64** [comment]
Thanks @Alhaitham for the suggestion.  It almost works perfectly, but it vertically shrinks the browser window every time.

**Comment by ysard** [comment]
Hi, it should be fixed in the next version (that will be uploaded in few minutes).
A checkbox is available in the options page.

@laniakea64 : By curiosity, on which system are you and which desktop interface?
I'm on Debian Jessie, with KDE 4.12.2 and I don't have this problem of modal window.

**Comment by laniakea64** [comment]
Works well, thank you for the fast fix! 😄 

> By curiosity, on which system are you and which desktop interface?

I'm using Xubuntu 16.04 (with Openbox window manager in XFCE instead of xfwm4)

**Comment by laniakea64** [comment]
Just noticed a minor wrinkle: the Options page always loads with the "Open Cookie Quick Manager in new tab" setting un-checked.  But that setting **does** get saved correctly, and changing it does work.

**Comment by ysard** [comment]
Well seen, it is fixed in 1095d85.
Thank you !
