### ISSUE TITLE
Show sameSite attribute

### ISSUE THREAD

**Issue by exploide** [ysard/cookie-quick-manager#40]
In the cookie details, flags like httpOnly and isSecure are shown. However, the sameSite attribute is not. Would be great to also see this.

**Comment by ysard** [comment]
Hi, yes this has been introduced in FF60, but the API is not yet able to handle this flag:

- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/set
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/get

According to this report: https://bugzilla.mozilla.org/show_bug.cgi?id=1351663, it will be available on Firefox63 which is planned for 2018-10-23. I will try to do my best to handle this :p

**Comment by ysard** [comment]
It will be available on the next release, near other flags:

![image](https://user-images.githubusercontent.com/14988285/47033236-928e2200-d174-11e8-988d-c1c2e75fb38d.png)
