### ISSUE TITLE
two more tooltip texts

### ISSUE THREAD

**Issue by practik** [ysard/cookie-quick-manager#42]
Hi ysard,

There are two buttons at the bottom of the CQM window that don't have tooltip texts: The "delete all" trashcan and the Bitcoin button. It would be nice if these had explanations like the other buttons.

I guess a tooltip for the trashcan is not 100% necessary because you get a big warning message when you click it, but it would be nice anyway. Some users may be afraid to click it at all because they know that it will delete something but they don't know what.

The Bitcoin button really does need a text IMO because it doesn't seem to do anything. Some users may click it and wonder: Did CQM just intall a Bitcoin miner on my computer?!?  (Related question: What does that button do? :p )

**Comment by ysard** [comment]
Hi, what version do you currently use?
I am surprised because these 2 tooltips were fixed some time ago (there was indeed a problem).

**Comment by practik** [comment]
CQM 0.3rc4 on FF 662.0 on macOS

Let me know if you want me to try a different version
