### ISSUE TITLE
How are you removing HttpOnly cookies?

### ISSUE THREAD

**Issue by iamadamdev** [ysard/cookie-quick-manager#43]
Hi,
May I ask how are you removing HttpOnly cookies?
I looked briefly through the source code and I didn't see anything special done to remove HttpOnly cookies:
https://github.com/ysard/cookie-quick-manager/blob/a37bc815ed3289fa1256889c5bbf7515642d173d/src/api.js#L219

I tried removing HttpOnly cookies programmatically in a Firefox addon but had no luck..

any ideas?

thanks

**Comment by ysard** [comment]
Hi, 
whether it's a HttpOnly cookie or not, you only need these arguments for the remove() function:
```
let params = {
    url: vAPI.getHostUrl(cookie), 
    name: cookie.name,
    storeId: cookie.storeId,
};
```
Take a look at the function getHostUrl() to forge your url with the attributes cookie.secure, cookie.domain, cookie.path.
You can add an additional key if First Party Domain is activated on the cookie you want to delete:
`firstPartyDomain`

**Comment by iamadamdev** [comment]
Interesting, that doesn't look very much different than what I have in my extension except mine is unable to remove HttpOnly cookies:

https://github.com/iamadamdev/bypass-paywalls-firefox/blob/master/background.js#L258

maybe the issue is something else then.

**Comment by ysard** [comment]
First, don't forget that firstPartyDomain is mandatory if the browser has first-party isolation enabled. Your code does not handle this case.
(https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/remove)

Then, pay attention to your inline condition that does not do what you would like it to do:

```
var a = true;
var b = a ? "https://" : "http://" + "path";
console.log(b);
>> "https://"
var b = (a ? "https://" : "http://") + "path";
console.log(b);
>> "https://path"
```
hoping that your bug is now resolved :)

**Comment by iamadamdev** [comment]
Thanks so much! that fixed it.
