### ISSUE TITLE
Cookie search and protection

### ISSUE THREAD

**Issue by nollinvoyd** [ysard/cookie-quick-manager#47]
Firefox 63.01, Windows 10 pro,

Perhaps I don't understand how the "Search a Domain" feature is supposed to work, but when I search for a word that is in the domain name, I get no results.

If possible, I think it also might be a good idea to have at least one of the following options, especially for those of us who aren't interested in anything more complicated than protecting cookies, and don't look forward to scrolling thru 100's of cookies each we we want to do so.

1.  Have a ""Protect Cookie/Unprotect Cookie" option on the tab context menu or tab drop down menu of the site you are currently viewing

2.  When I click on the toolbar button & open the "Cookie Quick Manager", I would like the list to automatically scroll to the cookie for the current website.  Perhaps by way of a checkbox on that interface enabling that option.

thanks

**Comment by ysard** [comment]
Hi, if you select the "Search cookies for: github.com" menu entry, you will only see domains linked to this site (including subdomains) and the cookies that refer to it.

For the example with github.com, there are 4 subdomains:
.github.com
.rawgithub.com
gist.github.com
github.com

If you check the "subdomains" checkbox, these 4 subdomains and their cookies will be merged under the master domain: github.com

Also, allowing a user to protect all the cookies of a domain without distinction seems to be a great idea in terms of user experience but, can lead to inconveniences such as the unnecessary persistence of tracking cookies...

**Comment by nollinvoyd** [comment]
Hi ysard 2,

I can't explain, but before I posted, no searches rendered any results.  Now it works properly :)

As far as allowing the user to protect all the cookies of a domain without distinction, I do get your point, but isn't that essentially what the "subdomains" checkbox does? Or maybe I don't understand?

This may not be possible, but how about this.  When you open "Manage all cookies", the domain name is automatically placed in the search field.  It would then be the users option to select the "subdomains" checkbox or not.  I'm lazy.

thanks.

**Comment by ysard** [comment]
Hi, 
The checkbox "sub domains" just simplifies the display by bringing together cookies managed by a single master domain (i.e. a domain whose cookies can be read by pages hosted on subdomains).

But if you do a right click on a domain (master or not, depending of the status of the option "sub domains"), yes, you can choose to protect all the cookies it it (and all session cookies in a future release).

>  When you open "Manage all cookies", the domain name is automatically placed in the search field.

This only happens if you click on "Search cookies for xxxx", not if you click on "Manage all cookies"; but I'm not sure I understand what you're proposing :)

**Comment by ysard** [comment]
A little cleaning in the issues. Shortcuts to protect cookies are available in the context menu that appears by right-clicking above a domain name.
