### ISSUE TITLE
missing resp. improvable features

### ISSUE THREAD

**Issue by AX-Turbo** [ysard/cookie-quick-manager#48]
Hi,

thank you very much for this useful add-on. What I´m missing resp. what´s improvable:
- a "delete all cookies" (apart from protected ones) quick option/hotkey
- "auto refresh" checkmark is _always_ disabled again after opening the options next time
- an optional deactivation of the warning message after clicking "delete all cookies" at options window
- the options window itself often forget it's prior size and position

**Comment by ysard** [comment]
Hi, thank you for your suggestions;

* a "delete all cookies" (apart from protected ones) quick option/hotkey
=> ok, what do you think of "Ctrl + D"?

* "auto refresh" checkmark is always disabled
So you would prefer that the status of this checkbox to be kept from one time to another?

* an optional deactivation of the warning message after clicking "delete all cookies"
It is already implemented in the options: *"Display an alert before removing cookies from entire browsing context(s)"*

* the options window itself often forget it's prior size and position
Yes i have some problems with this type of display...

**Comment by AX-Turbo** [comment]
- a "delete all cookies" (apart from protected ones) quick option/hotkey
=> _ok, what do you think of "Ctrl + D"?_

I´m not sure... if I press "Ctrl + D" right now, the browser opens a small "edit bookmark" field, so it's already reserved. Or must I still open the Manager main window first and press the keys there then (after you´ve added the hotkey combi)? I would just prefer the most simple "one-click/one-key" solution to delete all cookies except the locked ones. Sorry, noob here

- "auto refresh" checkmark is always disabled
_So you would prefer that the status of this checkbox to be kept from one time to another?_

Yes.

- an optional deactivation of the warning message after clicking "delete all cookies"
_It is already implemented in the options: "Display an alert before removing cookies from entire browsing context(s)"_

thanks for this hint, hadn't noticed that before.

**Comment by ysard** [comment]
In fact, the "suppr" key already allows you to delete cookies one by one.
"Ctrl + suppr" forces to release the mouse in order to simultaneously press these 2 keys.
The normal "Ctrl + D" behavior of adding a bookmark does not really make sense for a special page like that of an addon.

**Comment by ysard** [comment]
This issue seems resolved, you are free to reopen it if something needs to be fixed.
