### ISSUE TITLE
Allow editing cookie name

### ISSUE THREAD

**Issue by exploide** [ysard/cookie-quick-manager#49]
It appears to me that while I can edit the Value of a cookie, I cannot change its name. From time to time I use this functionality from Firefox dev tools. Copying and renaming cookies back and forth can be handy when testing session management of an application.

So I would like to ask having an editing capability for the cookie's name. (and maybe all the other fields that are not editable yet :stuck_out_tongue: e.g. Domain, Path, ...)

**Comment by exploide** [comment]
Oh, I just discovered the edit pencil unlock button... That does serve my purpose. Despite I found that a bit unintuitive.

**Comment by ysard** [comment]
Hi, yes I understand that it was not intuitive (I put a screenshot on AMO about it) but it is to understand that by changing the gray fields, you create a new cookie instead of just editing the one you are viewing :p
