### ISSUE TITLE
Protected cookies of private windows are protected but deleted after restart of Firefox

### ISSUE THREAD

**Issue by ghost** [ysard/cookie-quick-manager#52]
Hello developers,

I'm using version `0.4rc1`.

Protected cookies in Private windows are protected only within a Firefox session. So if I close Private windows and open new ones, they will be protected.

However If I restart Firefox, they will be lost.

May I ask if you could check?

Thank you for your hard wok,

**Comment by ysard** [comment]
Hi, this is a good point, 
indeed, in private browsing, all cookies are considered as session cookies and are deleted when the browser is closed.
It is not possible to my knowledge, to prevent erasing browsing data at the end of a private browsing.
This is a mechanism similar to the "keep cookies until Firefox closed" feature.

You should use a contextual identity container if you want to isolate your data while keeping it in time.
See: https://blog.mozilla.org/tanvi/2016/06/16/contextual-identities-on-the-web/

**Comment by ghost** [comment]
@ysard 

Thank you. I was trying to make my private-use extension which would set default cookies for sites. But Firefox was very difficult about self-host extensions. So I gave up.  :-(

I'm closing this issue. Thank you again for your help.
