### ISSUE TITLE
Fault: Incorrect site details show in the search box.

### ISSUE THREAD

**Issue by seanryan-seanryan** [ysard/cookie-quick-manager#6]
I was viewing the following web page:

https://www.talktalk.co.uk/my/billsandpayments?origin=myaccount.talktalk.co.uk

On clicking the extension toolbar icon, I get the prompt:
      Search cookie for: www.talktalk.co.uk
When I click that, the Cookie Quick Manager tab shows, but instead of the same text appearing in the search box, it contains only "co.uk" and all sites matching "co.uk" show in the Domains box instead of the site I was on.

Other sites are working OK for me.

Thanks for your effort on this extension.

**Comment by ysard** [comment]
Hi, thanks for reporting the bug, it should be fixed in the following release :)
Problems concerning the recovery of hostnames without their sub-domains will be much less frequent.
