### ISSUE TITLE
Export File

### ISSUE THREAD

**Issue by markwr** [ysard/cookie-quick-manager#61]
Using ver 0.4rc2-0.4rc3
Using Firefox 66.0.3
The following process is not working: Export / Save all to file. The standard file save dialog shows up (using cookies.json). I note the drive:\folder\ location and click OK. No error messages. The file does not exist on the drive. Next I changed Settings / Export Template: Netscape. Then I tried again Export / Save all to file. Cookies.txt does not exist on drive. However, Export / Copy all to clipboard, does work, both for .json and netscape .txt formats.

**Comment by markwr** [comment]
SOLVED. Firefox extension VTZilla was "pausing" the download of the file.

**Comment by ysard** [comment]
No problem, thank you for giving the solution.
