### ISSUE TITLE
Feature Request: Identify Container where Cookies Exist

### ISSUE THREAD

**Issue by seanryan-seanryan** [ysard/cookie-quick-manager#7]
In the Cookie Quick Manager tab/window, please can you display the name of the Container where the Cookies exist and provide a filter (search box) where users can type in a Container name. I am in the process of switching over to use different Containers for different websites (eg Shopping, Banking, etc) and the task I'm doing is trying to find in which Containers my cookies exist, then delete all those found in old/default/incorrect Containers. It is very time consuming and your extension could help greatly. 

I'd love to be able to MOVE a batch of  cookies from one Container to another (which would save me having to type in all my logon user details again)... but maybe that would be asking too much? PS I'm not a web developer, so I don't even know if the cookies would still "function" if moved to a new Container?

Thanks for your effort on this extension.

**Comment by ysard** [comment]
Hi, there is indeed both a bug and a lack of functionality for my addon about the containers that are under development in Firefox Nightly for the moment (it seems to me?).

I will be able to work on this with the addon available here:
https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

However, I will not have enough time in the next few days to take a serious look at it, so we'll have to wait a little ^^.


About batch changes, the idea could be to propose multiple selection of domains to be processed but it requires a lot more work...

**Comment by seanryan-seanryan** [comment]
Thanks for considering. Containers now exist in the live version of Firefox (I'm on 57.0.4 64-bit) and does not require that extension (I do not have the extension installed - though I've read that this feature did originally start it's life under that extension, and have never used Firefox Nightly). Under Options / Tabs, the last entry is "Enable Container tabs". I think it is unticked by default.

**Comment by scheinercc** [comment]
Just installed the add-on and this seems to have been implemented :)

**Comment by seanryan-seanryan** [comment]
As far as I can see, this has been _partially_ implemented: Under "Domains" and "Cookies" headings, the Container Icon is now displayed next to any cookie that's not located in Default. Under "Details" the relevant Container is named in the field "Store". So that's all good. What's missing is the request: **provide a filter (search box) where users can type in a Container name.** eg: I would like to be able to list cookies only for Container "Shopping".
@scheinercc:  Thanks for your interest in this item.

**Comment by ysard** [comment]
Hi, it will be fully implemented in the next release ;)
