### ISSUE TITLE
About Protecting Cookies

### ISSUE THREAD

**Issue by innkeeper9** [ysard/cookie-quick-manager#8]
I don't really know how to use this add-on. On the older Firefox I had two cookie add-ons one was to be able to protect individual cookies and the other was to be able to delete all but protected cookies on closing the browser.

I did, by accident, find the protect/unprotect all cookies in that little lock icon below the list of cookies, but when you highlight a cookie and click that lock are you protecting only that cookie [all the cookies that show as part of that] or are you protecting all cookies. Assuming it protects only the ones you are highlighting, can you then set Firefox to delete all cookies on close and will it keep the protected ones. Thanks for your help. Ruth

**Comment by thomecat** [comment]
I find the protection confusing also.  Please verify:  a closed padlock means open for deletion.  A open padlock means closed (locked) for deletion (not deleted when clearing all cookies.)  Also cookies must be protected one-by-one; there is no way to protect all cookies for a domain.

**Comment by ysard** [comment]
Hi, first of all, sorry for the delay in responding.
The protection of cookies is limited only to the current addon and deletions that can be made by the sites themselves.
This means that if you choose the browser option to delete all cookies when it closes, the addon will be unable to restore them (the method used by the browser does not send the necessary signal to notify the addon).
However, the addon is fully functional if you try to delete some cookies from the browser's "Cookies and Site Data" options.
In addition, in the addon options, you can choose to delete all cookies (except protected cookies) when restarting the browser.

The icons on the buttons were confusing, now they symbolize the current state of the selected cookie. In the new version there will also be a feature to protect all cookies in a domain.

With the hope to have answered your questions :)

**Comment by innkeeper9** [comment]
Thank you so very much!. Sorry it has been so long for a reply, but I just got back on the computer to do things other than email.  Now that I know it is an ‘open’ lock that indicates protection, I have been able to protect those cookies that I need to protect.  It is not really intuitive the way it is, very strange, after all in ‘life’ a locked door, protects the inside, a locked safe protects the contents inside, so having to ‘open’ the lock to protec t seems backward J

 

Ruth

**Comment by innkeeper9** [comment]
Thank you for the response. Someone did reply and it did help. It was just confusing that you have to have an ‘open’ lock on the cookie to protect it, not a closed lock. It just seems backwards, since many of us who are not really computer literate would make associations with the ‘real’ world, i.e. closed lock would equal protection and open lock non protect. But, now that I know, I can now protect the ones I need and have, so I am so very happy with the addon. Thank  you so much for all  your work on this!

**Comment by ysard** [comment]
Thank you for the encouragement;
I closed the issue ;)
